theme: jekyll-theme-cayman
title: checkout
header_image: assets/images/paymentspring_header_logo.svg
fav_icon: assets/images/paymentspring_favicon.png
inline_image: assets/images/paymentspring_inline_example.png
